const messages=document.getElementById("messages"),prompt=document.getElementById("prompt"),send=document.getElementById("send"),status=document.getElementById("status"),settings=document.getElementById("settings"),serverUrl=document.getElementById("serverUrl");
let mode="chat",history=[];
serverUrl.value=localStorage.getItem("vasilin_server_url")||"http://localhost:8787";
document.querySelectorAll(".mode").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".mode").forEach(x=>x.classList.remove("active"));b.classList.add("active");mode=b.dataset.mode;prompt.placeholder=mode==="chat"?"Напиши сообщение...":"Опиши изображение, которое нужно создать..."}));
document.getElementById("settingsBtn").addEventListener("click",()=>settings.showModal());
document.getElementById("saveSettings").addEventListener("click",()=>{const v=serverUrl.value.trim().replace(/\/$/,"");if(v)localStorage.setItem("vasilin_server_url",v)});
function addTextMessage(role,text){const w=document.createElement("div");w.className="message "+role;w.innerHTML='<div class="role">'+(role==="user"?"Ты":"ВасилинБилич AI")+'</div><div class="bubble"></div>';w.querySelector(".bubble").textContent=text;messages.appendChild(w);messages.scrollTop=messages.scrollHeight}
function addImageMessage(data){const w=document.createElement("div");w.className="message assistant";w.innerHTML='<div class="role">ВасилинБилич AI</div><div class="bubble imageBubble"></div>';const img=document.createElement("img");img.src="data:image/png;base64,"+data;w.querySelector(".bubble").appendChild(img);messages.appendChild(w);messages.scrollTop=messages.scrollHeight}
async function submit(){const text=prompt.value.trim();if(!text||send.disabled)return;addTextMessage("user",text);prompt.value="";send.disabled=true;status.textContent=mode==="chat"?"Думаю...":"Создаю изображение...";
try{const baseUrl=localStorage.getItem("vasilin_server_url")||"http://localhost:8787";if(mode==="chat"){const r=await window.vasilin.request(baseUrl,"/chat",{message:text,history});const answer=r.text||"Пустой ответ.";addTextMessage("assistant",answer);history.push({role:"user",content:text},{role:"assistant",content:answer})}else{const r=await window.vasilin.request(baseUrl,"/image",{prompt:text});addImageMessage(r.data)}status.textContent=""}catch(e){addTextMessage("assistant","Ошибка: "+e.message);status.textContent="Проверь адрес сервера и его доступность."}finally{send.disabled=false;prompt.focus()}}
send.addEventListener("click",submit);prompt.addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();submit()}});
